FROM maven:3.5.2-jdk-8-alpine AS MAVEN_TOOL_CHAIN
COPY pom.xml /tmp/
COPY src /tmp/src/
WORKDIR /tmp/
ENV SPRING_LOCAL_PORT=8080
ENV SPRING_DOCKER_PORT=4000

RUN mvn package


FROM tomcat:9.0-jre8-alpine
COPY --from=MAVEN_TOOL_CHAIN /tmp/target/*.war $CATALINA_HOME/webapps/accenture-techhub.war

EXPOSE 8080

CMD ["catalina.sh", "run"]